### PR TITLE
Fix grammatical erros in the Cantonese localization

### PR DESCRIPTION
**Pull request by laubonghaudoi**
Some translations in Cantonese are not correct. The sentences are ungrammatical.

### CODE REVIEW

**Comment by laubonghaudoi** [comment]
@backmeupplz @FiveBoroughs @krboktv Bumping this up. Could you please merge this simple PR? We are just fixing typos and it doesn't require any dependencies. Thank you!

**Comment by backmeupplz** [comment]
lgtm, I don't have the authority to merge this though

**Review by backmeupplz — APPROVED** [review]

**Comment by laubonghaudoi** [comment]
Thanks! Sorry I thought you are the maintainer of Shieldy. So who should I notify to merge this?

**Comment by backmeupplz** [comment]
@krboktv probably? Not sure

**Comment by laubonghaudoi** [comment]
I see. Because last time you were the one who merged the PR https://github.com/1inch/shieldy/pull/105, seems like the maintainer team has changed

**Pull request closed without merging**
